Add tomas's blog post (part i)
bisq-network/bisq-website pull request #154
Opened 2019-03-22 22:46 UTC by m52go

Blog post by @KanoczTomas. I think it's ready to go.

2019-03-22 23:24 UTC, KanoczTomas commented
@m52go this part of the commit looks like a left over from a previous post maybe?
excerpt: "The Bisq DAO enables value transfer and decision-making for the Bisq network. But it has several additional benefits too, which we'll focus on in this series.<br><br>In this post, Part I of this series, we'll discuss how Bisq's revenue model offers a new approach to funding open-source software development that, by design, avoids incentives to exploit user privacy altogether.<br><br>"

2019-03-22 23:58 UTC, m52go commented
@KanoczTomas you're right, thanks for catching that. I forgot to change. Fixed. 

Let me know if you prefer a different excerpt.

2019-03-23 00:08 UTC, ManfredKarrer requested changes

2019-03-23 00:08 UTC, ManfredKarrer commented on _posts/2019-03-22-how-to-set-up-bitcoin-regtest.md
> +---
excerpt is from prev. post

2019-03-23 00:08 UTC, ManfredKarrer commented on _posts/2019-03-22-how-to-set-up-bitcoin-regtest.md
> +---
Beside the excerpt utACK

2019-03-23 00:08 UTC, m52go commented on _posts/2019-03-22-how-to-set-up-bitcoin-regtest.md
> +---
Thanks, latest commit fixed that.

2019-03-23 00:10 UTC, m52go commented
@ManfredKarrer excerpt fixed in latest commit, would you mind formally accepting? I know you utACKed above but GitHub still shows "Changes requested"

2019-03-23 07:56 UTC, KanoczTomas commented
@m52go it still shows the old excerpt when I look at the latest commit.

2019-03-23 07:59 UTC, KanoczTomas commented
@m52go ah sorry, was looking at the wrong commit :) Text is fine, thank you! @ManfredKarrer it can go out.

2019-03-23 15:38 UTC, ManfredKarrer approved these changes
utACK

2019-03-23 15:38 UTC, merged