Add RSS feed hyperlink
bisq-network/bisq-website pull request #198
Opened 2019-07-26 17:12 UTC by huey735

I added hyperlinks to /blog/index.html and /_layouts/post.html.
I didn't make any change to /_layouts/post-report.html.

2019-08-01 17:24 UTC, m52go commented
@huey735 could we make the icon slightly smaller and better vertically aligned?

_Before_

![Screenshot from 2019-08-01 13-18-55](https://user-images.githubusercontent.com/735155/62313672-54da5b80-b45f-11e9-90af-162864499959.png)

_After_

![Screenshot from 2019-08-01 13-18-40](https://user-images.githubusercontent.com/735155/62313695-602d8700-b45f-11e9-9d32-07ff6fbc1c59.png)

May seem like a nit-pick for desktop but it makes a visible difference on smaller screens, especially phone screens. Below is the markup I used.

anchor tag -->

    display: inline-block;
    float: right;
    margin-top: 9px;

img tag -->

    width: 30px;

2019-08-02 09:54 UTC, huey735 reviewed
@m52go I added the css line inline, inside the html tags. I'm not sure if that's what you meant.

2019-08-05 16:39 UTC, m52go requested changes
@huey735 sorry I should've been more specific. I'd prefer to see CSS markup kept separate from HTML markup. I suggested HTML changes in-line. Here is the accompanying CSS markup:

```
.rss-link {
    float: right;
    width: 30px;
    height: auto;
}

.rss-link img {
    width: 100%;
}

.rss-link.blog-index {
    margin-top: 9px;
}

.rss-link.post {
    margin-top: 4px;
}

.post.type-post .dets h2, h1#blog-index-header {
    padding-right: 50px;
}
```

If you accept my HTML suggestions and add this markup to `css/styles.css` (ideally in the section marked 'blog' after line 707), it should be good.

2019-08-05 16:39 UTC, m52go commented on _layouts/post.html
> +        <a href="{{ site.url }}/blog/feed.atom" style="display: inline-block; float: right; margin-top: 4px;"><img src="{{ site.url}}/images/logo-rss.svg" class="rounded float-right" style="width: 30
```suggestion
       <a href="{{ site.url }}/blog/feed.atom" class="rss-link post"><img src="{{ site.url}}/images/logo-rss.svg"></a>
```

2019-08-05 16:39 UTC, m52go commented on blog/index.html
> +<a href="{{ site.url }}/blog/feed.atom" style="display: inline-block; float: right; margin-top: 9px;"><img src="{{ site.url}}/images/logo-rss.svg" class="rounded float-right" style="width: 30px;"></a
```suggestion
<a href="{{ site.url }}/blog/feed.atom" class="rss-link blog-index"><img src="{{ site.url}}/images/logo-rss.svg"></a>
```

2019-08-06 16:00 UTC, m52go commented
ACK

2019-08-06 16:00 UTC, m52go commented
I forgot to change the ID of the blog index page header in my suggestions, so I'll follow this merge with that small tweak.

2019-08-06 16:00 UTC, merged