Add French translation
bisq-network/bisq-website pull request #219
Opened 2019-08-26 17:10 UTC by huey735

2019-08-26 19:52 UTC, m52go requested changes
Lots of minor issues (mainly spacing), which I made suggestions to. Otherwise it makes the project look sloppy. In the future, please run the site locally and do a quick glance through the pages to make sure there aren't any lingering gremlins.

Also you have one commit related to outdated_translations here...please remove it (commit 20a08bcdb9ce2965c61b3c34681cf7c024cca2d0) since it's not related to this PR.

2019-08-26 19:52 UTC, m52go commented on _data/fr.yml
> +  pConceptualOverview: "<p class=\"bigger\">En langage simple<a href=\"https://docs.bisq.network/user-dao-intro.html\" target=\"_blank\" rel=\"noopener\">description</a> de la DAO.</p>"
```suggestion
  pConceptualOverview: "<p class=\"bigger\">En langage simple <a href=\"https://docs.bisq.network/user-dao-intro.html\" target=\"_blank\" rel=\"noopener\">description</a> de la DAO.</p>"
```

2019-08-26 19:52 UTC, m52go commented on _data/fr.yml
> +  pTechnicalOverview: "<p class=\"bigger\"><a href=\"https://docs.bisq.network/dao/specification.html\" target=\"_blank\" rel=\"noopener\">spécificité</a> du fonctionnement de la DAO de Bisq et du je
```suggestion
  pTechnicalOverview: "<p class=\"bigger\"><a href=\"https://docs.bisq.network/dao/specification.html\" target=\"_blank\" rel=\"noopener\">Spécificité</a> du fonctionnement de la DAO de Bisq et du jeton BSQ.</p>"
```

2019-08-26 19:52 UTC, m52go commented on _data/fr.yml
> +  pNetworkLoad: "<p class='monitor-note'>Pour connaître la sollicitation du réseau P2P, les métriques Tor et d'autres données réseau, veuillez visiter le site Web du <a href='https://monitor.bisq.net
```suggestion
  pNetworkLoad: "<p class='monitor-note'>Pour connaître la sollicitation du réseau P2P, les métriques Tor et d'autres données réseau, veuillez visiter le site Web du <a href='https://monitor.bisq.network' target='_blank'>contrôleur de réseau Bisq</a>.</p>"
```

2019-08-26 19:52 UTC, m52go commented on _data/fr.yml
> +      <li>Bisq n'est pas une entreprise. Il s'agit d'un projet open-source organisé sous la forme d'une<a href="https://docs.bisq.network/user-dao-intro.html#what-is-a-dao" target="_blank" rel="noope
```suggestion
      <li>Bisq n'est pas une entreprise. Il s'agit d'un projet open-source organisé sous la forme d'une <a href="https://docs.bisq.network/user-dao-intro.html#what-is-a-dao" target="_blank" rel="noopener">Organisation autonome décentralisée (DAO)</a>.
```

2019-08-26 19:52 UTC, m52go commented on _data/fr.yml
> +    <strong>Frais de minage</strong> <p>Un maker qui propose une offre ne paie que des frais de minage associés aux frais de transaction de l'échange. Un taker d'offre paie des frais de minage associ
```suggestion
    <strong>Frais de minage</strong> <p>Un maker qui propose une offre ne paie que des frais de minage associés aux frais de transaction de l'échange. Un taker d'offre paie des frais de minage associés aux frais de transaction de l'échange, et de la transaction de dépôt ainsi que de la transaction de paiement. C'est parce que les frais de minage fluctuent et qu'il est impossible pour celui qui sommet l'offre de savoir quels seront les frais de minage au moment où son offre sera acceptée.</p> <p>Bisq utilise <a href="https://bitcoinfees.earn.com/api/v1/fees/list" target="_blank">ce service</a> pour estimer les frais. Les utilisateurs peuvent voir  les frais de minage en vigueur après qu'ils aient créé ou accepté une offre.</p>
```

2019-08-26 19:52 UTC, m52go commented on _data/fr.yml
> +    <p>Sur Bisq, les arbitres déterminent les solutions aux litiges lors des échanges. Les arbitres doivent payer un montant très élevé en <a href="https://docs.bisq.network/dao/phase-zero.html" targ
```suggestion
    <p>Sur Bisq, les arbitres déterminent les solutions aux litiges lors des échanges. Les arbitres doivent payer un montant très élevé en <a href="https://docs.bisq.network/dao/phase-zero.html" target="_blank" rel="noopener">BSQ bond</a>, ce qui garantit des évaluations équitables et prévient la collusion avec les traders.</p> <p>Les arbitres sont choisis au hasard pour chaque transaction.</p> <p>Si le trader A ne confirme pas la réception d'un transfert en devises nationales dans le <a href='#trade-periods'>temps imparti</a>, un bouton pour contacter l'arbitre apparaîtra pour les deux traders. Le trader B pourra alors soumettre à l'arbitre la preuve qu'il a, dans les faits, envoyé la somme correspondante. Alternativement, si le trader B n'a jamais envoyé la somme requise, le trader A peut soumettre à l'arbitre la preuve que les fonds n'ont jamais été reçus.</p> <p>Les éléments de preuve soumis doivent être cryptographiquement sécurisés en utilisant <a href="https://tlsnotary.org/" target="_blank">PageSigner</a> ou des relevés bancaires signés numériquement. Si ces méthodes échouent, des voies plus traditionnelles peuvent être employées.</p> <p>D'après notre expérience, la grande majorité des litiges ne sont pas causés par des intentions malveillantes, mais par des problèmes mineurs tels que des problèmes de réseau, des bugs, des problèmes bancaires, d'utilisation, etc.</p> <p>Une fois que l'arbitre aura clarifié la situation, il signera l'adresse multisignature 2-sur-3 en faveur de la partie concernée.</p>
```

2019-08-26 19:52 UTC, m52go commented on _data/fr.yml
> +    <p>Comme mentionné plus haut, les arbitres doivent bloquer un <a href="https://docs.bisq.network/dao/phase-zero.html" target="_blank" rel="noopener">BSQ bond</a>élevé pour devenir arbitre en prem
```suggestion
    <p>Comme mentionné plus haut, les arbitres doivent bloquer un <a href="https://docs.bisq.network/dao/phase-zero.html" target="_blank" rel="noopener">BSQ bond</a> élevé pour devenir arbitre en premier lieu - beaucoup plus élevé que la limite de transaction. Si les deux traders ne sont pas d'accord avec la résolution d'un arbitre, ils peuvent demander la confiscation du BSQ bond de l'arbitre.</p> <p>S'il est établi qu'il y a eu collusion, l'arbitre qui s'est mal conduit perdra son cautionnement en BSQ bond. L'arbitre subit donc une perte importante, car le BSQ bond était beaucoup plus élevé que le montant obtenu en étant malhonnête.</p>
```

2019-08-26 19:52 UTC, m52go commented on _data/fr.yml
> +    <p>Jusqu'à présent, Bisq a intentionnellement évité d'offrir un moyen d'entrer en contact direct avec son pair de trading Il n'y a généralement pas besoin d'un tel mécanisme, et offrir un tel méc
```suggestion
    <p>Jusqu'à présent, Bisq a intentionnellement évité d'offrir un moyen d'entrer en contact direct avec son pair de trading Il n'y a généralement pas besoin d'un tel mécanisme, et offrir un tel mécanisme n'ouvrirait qu'une " boîte de Pandore " en matière de sécurité : les utilisateurs malveillants pourraient piéger leurs pairs par le bias d'un échange en direct sans utiliser Bisq, puis exploiter le manque de sécurité pour arnaquer l'autre personne, ou utiliser le canal direct pour d'autres activités frauduleuses (fraudes d'ingénierie sociale, spam, etc).</p> <p>Au lieu de cela, en cas de problèmes, les utilisateurs peuvent ouvrir un différend et le résoudre avec l'aide d'un arbitre. Il y a également le <a href='https://bisq.community' target='_blank'>forum de Bisq</a> et <a href='https://bisq.network/slack-invite' target='_blank'>le canal de discussion Slack</a> à la disposition des utilisateurs désireux d'obtenir de l'aide.</p> <p>Remarque : avec le lancement du <a href='https://github.com/bisq-network/proposals/issues/52' target='_blank'>nouveau protocole d' échange</a>, il y aura, cependant, un moyen pour les pairs de communiquer directement les uns avec les autres.</p>
```

2019-08-26 19:52 UTC, m52go commented on _data/fr.yml
> +    <p>La DAO de Bisq (organisation autonome décentralisée) est un système de gouvernance décentralisé pour le logiciel Bisq. Il prend la place d'une entreprise. Comment un logiciel décentralisé peut
```suggestion
    <p>La DAO de Bisq (organisation autonome décentralisée) est un système de gouvernance décentralisé pour le logiciel Bisq. Il prend la place d'une entreprise. Comment un logiciel décentralisé peut-il être efficace s'il est toujours contrôlé par une seule entité, comme une entreprise?</p> <p>Un logiciel décentralisé ne sert à rien sans une gouvernance décentralisée.</p> <p>C'est pourquoi Bisq n'est pas une société ou une entité juridique de quelque nature que ce soit, elle est plutôt organisée comme un DAO. La DAO s'occupe du financement et de l'élaboration de la stratégie du logiciel afin de permettre au réseau Bisq de prospérer et, en même temps, de le renforcer contre les attaques contre ses infrastructures qui sont le moteur de sa direction et son fonctionnement.</p> <p>En résumé, la DAO de Bisq permet à Bisq de renforcer encore sa résistance à la censure, un <a href='https://docs.bisq.network/intro.html' target='_blank'>principe fondateur du projet</a> depuis sa genèse.</p> <p>En savoir plus sur la DAO de Bisq dans <a href='https://docs.bisq.network/user-dao-intro.html' target='_blank'>ce document de présentation</a>.</p>
```

2019-08-26 19:52 UTC, m52go commented on _data/fr.yml
> +  pOtherQuestions: "<p>Veuillez poster votre question sur <a href=\"https://bisq.community/\" target=\"_blank\"> le Forum de Bisq</a> ou<a href='https://bisq.network/slack-invite' target='_blank'>sur
```suggestion
  pOtherQuestions: "<p>Veuillez poster votre question sur <a href=\"https://bisq.community/\" target=\"_blank\"> le Forum de Bisq</a> ou <a href='https://bisq.network/slack-invite' target='_blank'>sur le canal de discussion Slack</a>.</p>"
```

2019-08-26 19:52 UTC, m52go commented on _data/fr.yml
> +    <p>“<a href="https://en.bitcoin.it/wiki/Multisignature" target="_blank">Multisig</a>”, comme on l'appelle, est intégré à Bitcoin comme une simple version d'un contrat intelligent. Une adresse mul
```suggestion
    <p>“<a href="https://en.bitcoin.it/wiki/Multisignature" target="_blank">Multisig</a>”, comme on l'appelle, est intégré à Bitcoin comme une simple version d'un contrat intelligent. Une adresse multisig est générée avec plusieurs clés publiques avec une spécification du nombre de clés à signer pour libérer les fonds.</p> <p>Bisq utilise des adresses multisig 2-sur-3. Cela signifie que trois clés publiques sont utilisées pour créer l'adresse de paiement (celle de l'acheteur, du vendeur et d'un arbitre) et que la transaction doit être signée par deux des trois parties pour que les fonds soient libérés.</p> <p>En pratique, l'acheteur et le vendeur signent chacun la transaction pour débloquer les fonds. Mais en cas de litige, un arbitre se rangera du côté de l'une des parties pour fournir la deuxième signature nécessaire à la libération des fonds.</p>
```

2019-08-26 19:52 UTC, m52go commented on _data/fr.yml
> +    </ul> <p>Les virements bancaires nationaux sont pris en charge dans tous les pays.</p> <p>Yvous pouvez proposer un nouveau moyen de paiement sur le forum</a>, <a href='https://bisq.network/slack-
```suggestion
    </ul> <p>Les virements bancaires nationaux sont pris en charge dans tous les pays.</p> <p>Yvous pouvez proposer un nouveau moyen de paiement sur le forum</a>, <a href='https://bisq.network/slack-invite' target='_blank'>Slack</a>, ou <a href='https://github.com/bisq-network/bisq/issues' target='_blank'>GitHub</a>.</p>
```

2019-08-26 19:52 UTC, m52go commented on _data/fr.yml
> +  runningWindows: Vous semblez utiliser Windows.
```suggestion
  runningWindows: Vous semblez utiliser Windows
```

2019-08-26 19:52 UTC, m52go commented on _data/fr.yml
> +  runningMac: Vous semblez utiliser un Mac.
```suggestion
  runningMac: Vous semblez utiliser un Mac
```

2019-08-26 19:52 UTC, m52go commented on _data/fr.yml
> +  runnigDebian: Vous semblez utiliser Debian/Ubuntu.
```suggestion
  runnigDebian: Vous semblez utiliser Debian/Ubuntu
```

2019-08-26 19:52 UTC, m52go commented on _data/fr.yml
> +  runningRedHat: Vous semblez utiliser Debian/Ubuntu.
```suggestion
  runningRedHat: Vous semblez utiliser Debian/Ubuntu
```

2019-08-26 19:52 UTC, m52go commented on _data/fr.yml
> +    <p>Bisq est toujours à la recherche de développeurs, de concepteurs et d'experts en sécurité hautement qualifiés pour se joindre à notre <a href="https://bisq.network/community/">communauté</a>.
```suggestion
    <p>Bisq est toujours à la recherche de développeurs, de concepteurs et d'experts en sécurité hautement qualifiés pour se joindre à notre <a href="https://bisq.network/community/">communauté</a>. Si vous souhaitez contribuer à l'amélioration de Bisq, il existe de nombreuses façons de <a href="https://docs.bisq.network/contributor-checklist.html" target="_blank" rel="noopener">contribuer</a>. Nous aimerions beaucoup <a href="https://bisq.network/community/">entendre parler de vous</a>!</p> <p>Notre <a href="https://bisq.network/roadmap/">feuille de route</a> fournit une vue d'ensemble des fonctionnalités complexes et des étapes importantes sur le chemin vers Bisq v1.0.</p>
```

2019-08-26 19:52 UTC, m52go commented on _includes/main_nav_tr.html
> +     <!-- Outdated translation alert tool tag-->
Please remove the commit with this change, since there's already another PR with this change.

2019-08-28 17:03 UTC, huey735 commented
Closing because it contains unrelated commit.

2019-08-28 17:03 UTC, closed without merging

2019-08-28 17:05 UTC, m52go commented
@huey735 you should be able to remove the commit and then force-push (`git push -f <remote> addFrenchTranslation`). That would allow you to easily implement all my suggested edits, instead of doing them over on your own and me reviewing again.