Add blog post on cycle 5
bisq-network/bisq-website pull request #253
Opened 2019-09-19 13:54 UTC by m52go

Summarize results and call for more due diligence (leo/lio incident). @erciccione you're also welcome to review...I couldn't assign you as a reviewer.

2019-09-19 15:41 UTC, erciccione approved these changes
Looks good to me.

ACK

2019-09-19 19:06 UTC, devinbileck approved these changes
utACK
Looks good! Just a few minor corrections.

2019-09-19 19:06 UTC, devinbileck commented on _posts/2019-09-18-cycle-5-results.md
> +The person taking on this role will periodically purchase BSQ with the BTC accumulated in the donation address. They will be be assigned to the [corresponding role issue](https://github.com/bisq-netw
```suggestion
The person taking on this role will periodically purchase BSQ with the BTC accumulated in the donation address. They will be assigned to the [corresponding role issue](https://github.com/bisq-network/roles/issues/80){:target="_blank"} shortly, where you will see monthly updates.
```

2019-09-19 19:06 UTC, devinbileck commented on _posts/2019-09-18-cycle-5-results.md
> +**Improve Bisq testing framworks**
```suggestion
**Improve Bisq testing frameworks**
```

2019-09-20 16:20 UTC, m52go commented
Thanks for reviewing! I got so wrapped in detailing proposals that I forgot to add a summary of the cycle's time frame and economics. Added those in another commit.

2019-09-20 17:44 UTC, erciccione requested changes
Yeah the summary is definitely nice to have. Now the PR only need to be squashed and then will be ok IMO

2019-09-23 08:31 UTC, erciccione approved these changes

2019-09-23 13:44 UTC, merged