Dark mode
bisq-network/bisq-website pull request #378
Opened 2020-07-22 18:32 UTC by pedromvpg

Add darkmode functionality and new client screen images.

2020-07-24 06:10 UTC, cbeams commented
This looks great, wow. A few notes:

1. Consider defaulting to dark mode when the OS is in dark mode; see https://stackoverflow.com/a/52986538 for the CSS.
2. Swap the homepage screenshot to Bisq in dark mode when website is in dark mode
3. Text in the input field for the Markets page is hard to see note how the 'eur' text is dark-on-dark below:

<img width="764" alt="image" src="https://user-images.githubusercontent.com/301810/88364995-ed5e9f80-cd84-11ea-8afa-4067d02aabba.png">

2020-07-27 07:13 UTC, cbeams commented
Defaulting to dark mode seems to work well (I'm looking at https://deploy-preview-378--bisq-website.netlify.app/). One nit is that when dark mode is active, the menu toggle reads 'Dark', and when light mode is active, it reads 'Light'. Shouldn't this be the other way around? i.e. an affordance should advertise the state change that will occur if you make use of it (click it), as opposed to advertising the current state. Also, a common idiom I've seen is the use of a crescent moon symbol in the upper right for toggling dark / light mode. It takes up less real estate and is somehow more intuitive (to me) than just a textual 'light/dark' link.

2020-07-27 20:42 UTC, m52go commented
Just want to say I've been watching this PR -- it looks amazing! 

I see the markets dropdown text has been fixed, but the screenshots on the front page are still in light mode. Also I have agree with cbeams' comment above about flipping the dark mode toggle action and considering symbols instead of text for the label.

2020-07-30 03:29 UTC, m52go requested changes
I had another look and everything seems to work fine. It looks so good (!).

I've attached a couple of nitpicks in the JavaScript...there's a stray `console.out()` still there from debugging and an unused condition in 2 of the if statements.

That's it from my end. @pedromvpg I will ACK once you make those changes, and merge a short while afterward if there's no other feedback.

2020-07-30 03:29 UTC, m52go commented on _layouts/default.html
> +      if (Cookies.get('darkmode') === undefined && window.matchMedia && window.matchMedia('(prefers-color-scheme: light)').matches) {
```suggestion
      if (Cookies.get('darkmode') === undefined && window.matchMedia('(prefers-color-scheme: light)').matches) {
```

2020-07-30 03:29 UTC, m52go commented on _layouts/default.html
> +        console.log('no cookie');
```suggestion

```

2020-07-30 03:29 UTC, m52go commented on _layouts/default.html
> +      }else if(Cookies.get('darkmode') === undefined && window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
```suggestion
      }else if(Cookies.get('darkmode') === undefined && window.matchMedia('(prefers-color-scheme: dark)').matches) {
```

2020-07-31 20:57 UTC, m52go approved these changes
ACK

2020-07-31 20:57 UTC, merged